ALTER TABLE `installations` ADD COLUMN IF NOT EXISTS `customerName` VARCHAR(191) NULL;
ALTER TABLE `installations` ADD COLUMN IF NOT EXISTS `lokasi` VARCHAR(191) NULL;
ALTER TABLE `installations` ADD COLUMN IF NOT EXISTS `notes` TEXT NULL;
ALTER TABLE `installations` MODIFY COLUMN `picInstalasi` VARCHAR(191) NOT NULL DEFAULT '';
